### ISSUE TITLE
[BUG] Failed to install package python3-libcamera, package manager exited with code 100

### ISSUE THREAD

**Issue by phigjm** [Duet3D/SpyglassWebcamServerPlugin#1]
Installing the plugin by uploading the zip to a fresh duet install of duet 3.5 rc3 results into a 
`Failed to install package python3-libcamera, package manager exited with code 100`

Installing the library manually 
`sudo apt install python3-libcamera` or `sudo apt install python3-libcamera2`
results into an Error:
`E: Unable to locate package python3-libcamera`

Retrying this process with another fresh install  allows me to install `python3-libcamera` before installing the plugin. afterwards this option is gone.

**Comment by chrishamm** [comment]
As stated in the README file you need a Debian Bookworm-based image for this plugin. Previous RPi images do not provide the dependency which leads to this problem. See https://forum.duet3d.com/topic/34825/new-experimental-duetpi-bookworm-builds-available
